version: "3.8"

services:
  nextjs:
    build:
      context: . # Route to Dockerfile
    container_name: lgrt_app
    network_mode: host # Use host network
    environment:
      NEXTAUTH_URL: "http://localhost:3000" # URL base to NextAuth
    restart: always
